export default {
  AUTH: 'AUTH',

  USERS: 'USERS',

  SPAREPARTS: 'SPAREPARTS',
  SERVICES: 'SERVICES',
  SERVICE_REQUESTS: 'SERVICE_REQUESTS',

  ENQUIRIES: 'ENQUIRIES',
  CARS: 'CARS',
  CONSTANTS: 'CONSTANTS',
};
